[package]
name = "binpeek"
version = "0.2.2"
edition = "2021"
description = "A fast terminal-based binary file inspector for PE, ELF and Mach-O"
license = "MIT"
keywords = ["binary", "inspector", "pe", "elf", "tui"]
categories = ["command-line-utilities", "development-tools"]
authors = ["Kleshzz <https://github.com/Kleshzz>"]
repository = "https://github.com/Kleshzz/binpeek"
homepage = "https://kleshzz.github.io/binpeek"
exclude = ["/docs", ".github"]
rust-version = "1.88.0"

[dependencies]
goblin = "0.10.5"
capstone = "0.14"
crossterm = "0.29"
ratatui = "0.30"
clap = { version = "4.5", features = ["derive"] }

[profile.release]
opt-level = 3
lto = true
strip = true
codegen-units = 1
panic = "abort"
overflow-checks = false